# Generated by Django 5.1.4 on 2025-01-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patient_age_patient_gender_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Hematologists', 'Hematologists'), ('Infectious Disease Specialists', 'Infectious Disease Specialists'), ('Nephrologists', 'Nephrologists'), ('Neurologists', 'Neurologists'), ('Obstetricians/Gynecologists', 'Obstetricians/Gynecologists'), ('Oncologists', 'Oncologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic Surgeons', 'Orthopedic Surgeons'), ('Otolaryngologists', 'Otolaryngologists'), ('Pathologists', 'Pathologists'), ('Pediatricians', 'Pediatricians'), ('Psychiatrists', 'Psychiatrists'), ('Pulmonologists', 'Pulmonologists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists'), ('Urologists', 'Urologists')], max_length=50)),
                ('keywords', models.TextField(help_text='Comma-separated keywords related to this specialization')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomDepartmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctorspecialization')),
            ],
        ),
    ]
