# Generated by Django 5.2.dev20241203141516 on 2025-02-05 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_doctor_available_times_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
