# Generated by Django 5.2.dev20241203141516 on 2025-02-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_doctoravailability_date_and_more'),
        ('hospital', '0020_doctorspecialization_symptomdepartmentmapping'),
    ]

    operations = [
    ]
