# Generated by Django 5.2.dev20241203141516 on 2025-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_patient_age_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Hematologists', 'Hematologists'), ('Infectious Disease Specialists', 'Infectious Disease Specialists'), ('Nephrologists', 'Nephrologists'), ('Neurologists', 'Neurologists'), ('Obstetricians/Gynecologists', 'Obstetricians/Gynecologists'), ('Oncologists', 'Oncologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic Surgeons', 'Orthopedic Surgeons'), ('Otolaryngologists', 'Otolaryngologists'), ('Pathologists', 'Pathologists'), ('Pediatricians', 'Pediatricians'), ('Psychiatrists', 'Psychiatrists'), ('Pulmonologists', 'Pulmonologists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists'), ('Urologists', 'Urologists')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='time_slot',
            field=models.CharField(default='default_time', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
